#!/usr/bin/python3 -I
import os
import sys
sys.path.insert(0, "/usr/local/lib/4tw")
from appliance import retry_wifi
if len(sys.argv) != 1 or os.geteuid() != 0:
    raise SystemExit(2)
raise SystemExit(0 if retry_wifi() else 1)
