[Login]
NAutoVTs=0
ReserveVT=0
HandlePowerKey=poweroff
PowerKeyIgnoreInhibited=yes
HandleSuspendKey=ignore
HandleHibernateKey=ignore
HandleLidSwitch=ignore
HandleLidSwitchExternalPower=ignore
HandleLidSwitchDocked=ignore
